const BREADBOARD_ROW_LENGTH = 5;
const BREADBOARD_NUM_ROWS = 30;
const BREADBOARD_NUM_SECTIONS = 2;

const BREADBOARD_POINT_SIZE = 32;
const BREADBOARD_POINT_DISTANCE = 16;
const BREADBOARD_ROW_DISTANCE = BREADBOARD_POINT_SIZE + BREADBOARD_POINT_DISTANCE;

const BREADBOARD_SECTIONS_SPACE = BREADBOARD_ROW_DISTANCE * 2;
